package ddob.game.table;

public enum AttackResult {
    NO_EFFECT,
    US_DISRUPTED,
    GERMAN_DISRUPTED,
    GERMAN_DISRUPTED_AND_OPTIONAL_ATTRITION,
    GERMAN_ELIMINATED,
    GERMAN_ELIMINATED_AND_TACTICAL_REINFORCEMENT,
    GERMAN_DEPTH_ELIMINATED_AND_UNIT_DISRUPTED,
    GERMAN_DEPTH_ELIMINATED_AND_UNIT_ELIMINATED,
    GERMAN_GAIN_DEPTH,
    GERMAN_GAIN_DEPTH_AND_US_DISRUPTED
}
